image: python:3.10-buster

stages:
  - build
  - test
  - checkstyle
  - typecheck

build:
    stage: build
    script:
      - echo "build phase..."
      - uname -a

test:
    stage: test
    before_script:
      - pip install -r requirements-dev.txt
    script:
      - echo "Running tests"
        #    runs all tests in the tests directory that end with _test.py
      - pytest -v tests/
      - echo "Tests completed"

checkstyle:
    stage: checkstyle
    script:
      - echo "Running checkstyle"
      - pip install pycodestyle
      - pycodestyle --max-line-length=120 --ignore=E501,E731 .
      - echo "Checkstyle completed"

typecheck:
    stage: typecheck
    before_script:
      - pip install -r requirements-dev.txt
    script:
      - echo "Running type checker"
      - mypy --ignore-missing-imports --strict ./multi_modal_edge_ai/
      - echo "Type checkin completed"

