image: python:3.10-buster

stages:
  - build
  - test
  - checkstyle

build:
    stage: build
    script:
      - echo "build phase..."
      - uname -a

test:
    stage: test
    script:
      - echo "Running tests"
        #    runs all tests in the tests directory that end with _test.py
      - pip install pytest
      - pytest -v
      - echo "Tests completed"

checkstyle:
    stage: checkstyle
    script:
      - echo "Running checkstyle"
      - pip install pycodestyle
      - pycodestyle --max-line-length=120 --ignore=E501,E731 .
      - echo "Checkstyle completed"