image: python:3.10-buster

stages:
  - build
  - test
  - checkstyle
  - typecheck

build:
  stage: build
  script:
    - echo "build phase..."
    - uname -a

test:
  stage: test
  before_script:
    - pip install -r requirements-dev.txt
  script:
    - echo "Running tests"
    - pip install coverage pytest pytest-cov
    - python -m pytest --cov=multi_modal_edge_ai --cov-report term --cov-report xml:coverage.xml
    - coverage report -m
    - coverage html
    #    runs all tests in the tests directory that end with _test.py
    - echo "Tests completed"
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - htmlcov/

checkstyle:
  stage: checkstyle
  script:
    - echo "Running checkstyle"
    - pip install pycodestyle
    - pycodestyle --max-line-length=120 --ignore=E731 ./multi_modal_edge_ai
    - echo "Checkstyle completed"

typecheck:
  stage: typecheck
  before_script:
    - pip install -r requirements-dev.txt
  script:
    - echo "Running type checker"
    - mypy --ignore-missing-imports ./multi_modal_edge_ai/
    - echo "Type checkin completed"

