image: python:3.10-buster

stages:
  - build
  - test
  - checkstyle
  - typecheck

variables:
  SSH_SERVER: "user@IP"
  LOCAL_PORT: "27017"
  REMOTE_PORT: "27018"

build:
  stage: build
  script:
    - echo "build phase..."
    - uname -a

test:
  stage: test
  before_script:
    - pip install -r requirements-dev.txt
    - pip install coverage pytest pytest-cov
    - apt-get update && apt-get install -y sshpass
  script:
    - ls -la
    - echo "Running tests"
    - sshpass -p 'password' ssh -o StrictHostKeyChecking=no -fN -L $LOCAL_PORT:localhost:$REMOTE_PORT $SSH_SERVER &
    - python -m pytest --cov=multi_modal_edge_ai --cov-report term --cov-report xml:coverage.xml
    - coverage report -m
    - coverage html
    - echo "Tests completed"
  after_script:
    - pkill -f "$SSH_SERVER"
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - htmlcov/

checkstyle:
  stage: checkstyle
  script:
    - echo "Running checkstyle"
    - pip install pycodestyle
    - pycodestyle --max-line-length=120 --ignore=E731 ./multi_modal_edge_ai
    - echo "Checkstyle completed"

typecheck:
  stage: typecheck
  before_script:
    - pip install -r requirements-dev.txt
  script:
    - echo "Running type checker"
    - mypy --ignore-missing-imports ./multi_modal_edge_ai/
    - echo "Type checkin completed"
